import { type ReactNode, useMemo } from 'react'
import { ThemeContext } from './ThemeContextBase'
import type { ThemeContextValue } from './ThemeContext.types'
import { usePackageJson } from '@defalt/utils/hooks/usePackageJson'

export function ThemeProvider({ children }: { children: ReactNode }) {
  const {
    packageJson,
    setPackageJson,
    effectiveNavigationLayoutValue,
    navigationLayoutOptions,
    headerSettingsError,
    handleHeaderNavigationLayoutChange,
    headerAndFooterColorValue,
    headerAndFooterColorOptions,
    handleHeaderAndFooterColorChange,
    titleFontValue,
    titleFontOptions,
    handleTitleFontChange,
    bodyFontValue,
    bodyFontOptions,
    handleBodyFontChange,
    signupHeadingValue,
    handleSignupHeadingChange,
    signupSubheadingValue,
    handleSignupSubheadingChange,
    subheaderStyleValue,
    subheaderStyleOptions,
    handleSubheaderStyleChange,
    headerTextValue,
    handleHeaderTextChange,
    backgroundImageEnabled,
    handleBackgroundImageToggle,
    showFeaturedPosts,
    handleShowFeaturedPostsToggle,
    postFeedStyleValue,
    postFeedStyleOptions,
    handlePostFeedStyleChange,
    showImagesInFeed,
    handleShowImagesInFeedToggle,
    showAuthor,
    handleShowAuthorToggle,
    showPublishDate,
    handleShowPublishDateToggle,
    showPublicationInfoSidebar,
    handleShowPublicationInfoSidebarToggle,
    showPostMetadata,
    handleShowPostMetadataToggle,
    enableDropCapsOnPosts,
    handleEnableDropCapsOnPostsToggle,
    showRelatedArticles,
    handleShowRelatedArticlesToggle,
  } = usePackageJson()

  const value = useMemo<ThemeContextValue>(() => ({
    packageJson,
    onPackageJsonChange: setPackageJson,
    navigationLayoutValue: effectiveNavigationLayoutValue,
    navigationLayoutOptions,
    navigationLayoutError: headerSettingsError,
    onNavigationLayoutChange: handleHeaderNavigationLayoutChange,
    headerAndFooterColorValue,
    headerAndFooterColorOptions,
    onHeaderAndFooterColorChange: handleHeaderAndFooterColorChange,
    titleFontValue,
    titleFontOptions,
    onTitleFontChange: handleTitleFontChange,
    bodyFontValue,
    bodyFontOptions,
    onBodyFontChange: handleBodyFontChange,
    headerStyleValue: subheaderStyleValue,
    headerStyleOptions: subheaderStyleOptions,
    onHeaderStyleChange: handleSubheaderStyleChange,
    headerTextValue,
    onHeaderTextChange: handleHeaderTextChange,
    backgroundImageEnabled,
    onBackgroundImageToggle: handleBackgroundImageToggle,
    showFeaturedPosts,
    onShowFeaturedPostsToggle: handleShowFeaturedPostsToggle,
    postFeedStyleValue,
    postFeedStyleOptions,
    onPostFeedStyleChange: handlePostFeedStyleChange,
    showImagesInFeed,
    onShowImagesInFeedToggle: handleShowImagesInFeedToggle,
    showAuthor,
    onShowAuthorToggle: handleShowAuthorToggle,
    showPublishDate,
    onShowPublishDateToggle: handleShowPublishDateToggle,
    showPublicationInfoSidebar,
    onShowPublicationInfoSidebarToggle: handleShowPublicationInfoSidebarToggle,
    showPostMetadata,
    onShowPostMetadataToggle: handleShowPostMetadataToggle,
    enableDropCapsOnPosts,
    onEnableDropCapsOnPostsToggle: handleEnableDropCapsOnPostsToggle,
    showRelatedArticles,
    onShowRelatedArticlesToggle: handleShowRelatedArticlesToggle,
    signupHeadingValue,
    onSignupHeadingChange: handleSignupHeadingChange,
    signupSubheadingValue,
    onSignupSubheadingChange: handleSignupSubheadingChange,
  }), [
    packageJson,
    setPackageJson,
    effectiveNavigationLayoutValue,
    navigationLayoutOptions,
    headerSettingsError,
    handleHeaderNavigationLayoutChange,
    headerAndFooterColorValue,
    headerAndFooterColorOptions,
    handleHeaderAndFooterColorChange,
    titleFontValue,
    titleFontOptions,
    handleTitleFontChange,
    bodyFontValue,
    bodyFontOptions,
    handleBodyFontChange,
    subheaderStyleValue,
    subheaderStyleOptions,
    handleSubheaderStyleChange,
    headerTextValue,
    handleHeaderTextChange,
    backgroundImageEnabled,
    handleBackgroundImageToggle,
    showFeaturedPosts,
    handleShowFeaturedPostsToggle,
    postFeedStyleValue,
    postFeedStyleOptions,
    handlePostFeedStyleChange,
    showImagesInFeed,
    handleShowImagesInFeedToggle,
    showAuthor,
    handleShowAuthorToggle,
    showPublishDate,
    handleShowPublishDateToggle,
    showPublicationInfoSidebar,
    handleShowPublicationInfoSidebarToggle,
    showPostMetadata,
    handleShowPostMetadataToggle,
    enableDropCapsOnPosts,
    handleEnableDropCapsOnPostsToggle,
    showRelatedArticles,
    handleShowRelatedArticlesToggle,
    signupHeadingValue,
    handleSignupHeadingChange,
    signupSubheadingValue,
    handleSignupSubheadingChange,
  ])

  return (
    <ThemeContext.Provider value={value}>
      {children}
    </ThemeContext.Provider>
  )
}
